<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\core\AriaSignature.Application\AriaSignature.Application.csproj" />
    <ProjectReference Include="..\..\core\AriaSignature.Domain\AriaSignature.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="..\..\..\icon.png" Link="Assets\icon.png" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

</Project>
