<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>AriaSignature.ServiceBootstrap</RootNamespace>
    <AssemblyName>AriaSignature.ServiceBootstrap</AssemblyName>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\core\AriaSignature.WindowsServiceSetup\AriaSignature.WindowsServiceSetup.csproj" />
  </ItemGroup>

</Project>
